version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bitbarg_task
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - app-network
redis:
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - ./redis:/data
  networks:
    - app-network

volumes:
  postgresql:
  redis:

networks:
  app-network:
